name: GitHub Space Shooter

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # Tombol untuk menjalankan manual

permissions:
  contents: write    # SANGAT PENTING: Mengizinkan bot menyimpan file gambar ke repo

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Wajib ada agar riwayat commit terbaca

      - name: Generate Space Shooter Animation
        uses: czl9707/gh-space-shooter@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'space-shooter.gif' # Disimpan dalam format GIF
